name: Rollback CI/CD Workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to rollback'
        required: true
        default: 'cicd-sqitch'

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: List Repository Files
        run: |
          echo "Repository structure:"
          find . -type f
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: List Repository Files
        run: |
          echo "Repository structure:"
          find . -type f
          echo "\nDeploy directory contents:"
          find ./deploy -type f -name "*.sql"
          echo "\nRevert directory contents:"
          find ./revert -type f -name "*.sql"
          echo "\nVerify directory contents:"
          find ./verify -type f -name "*.sql"
          
      - name: Copy Sqitch files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 156.67.105.82
          username: root
          password: 1a2s3d4f5g@1993
          source: |
            ./sqitch.plan
            ./deploy/add_lodu.sql
            ./deploy/create_lodu.sql
            ./revert/add_lodu.sql
            ./revert/create_lodu.sql
            ./verify/add_lodu.sql
            ./verify/create_lodu.sql
          target: /root/deployment/sqitch
          strip_components: 0

      - name: Rollback Database and Restart Application
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 156.67.105.82
          username: root
          password: 1a2s3d4f5g@1993
          envs: DB_PASSWORD
          script: |
            echo "Stopping current application..."
            systemctl stop sqitch-spring-service.service || echo "Service not running"

            echo "Restoring previous JAR..."
            if [ -f "/root/deployment/backups/sqitch-test-0.0.1-SNAPSHOT.jar" ]; then
              cp /root/deployment/backups/sqitch-test-0.0.1-SNAPSHOT.jar /root/deployment/sqitch-test-0.0.1-SNAPSHOT.jar
              echo "Previous JAR restored successfully."
            else
              echo "No previous JAR found! Rollback skipped."
              exit 1
            fi

            echo "Installing Sqitch if not already installed..."
            apt update && apt install -y sqitch libdbd-mysql-perl

            echo "Fetching previous Sqitch migration tag..."
            cd /root/deployment/sqitch
            PREV_TAG=$(sqitch log --reverse -n 2 db:mysql://admin:password%40123@localhost/cicdpipeline | awk 'NR==4 {print $1}')

            if [ -n "$PREV_TAG" ]; then
              echo "Reverting database to $PREV_TAG..."
              sqitch revert db:mysql://admin:password%40123@localhost/cicdpipeline --to $PREV_TAG
              echo "Database rollback successful."
            else
              echo "No previous Sqitch migration found! Skipping DB rollback."
            fi

            echo "Reloading systemd and restarting application..."
            systemctl daemon-reexec
            systemctl start sqitch-spring-service.service
            systemctl status sqitch-spring-service.service || echo "Failed to start service"
