name: Rollback CI/CD Workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to rollback'
        required: true
        default: 'cicd-sqitch'

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: Rollback Database and Restart Application
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 156.67.105.82
          username: root
          password: 1a2s3d4f5g@1993
          envs: DB_PASSWORD
          script: |
            echo "Stopping current application..."
            systemctl stop sqitch-spring-service.service || echo "Service not running"

            echo "Restoring previous JAR..."
            if [ -f "/root/deployment/backups/sqitch-test-0.0.1-SNAPSHOT.jar" ]; then
              cp /root/deployment/backups/sqitch-test-0.0.1-SNAPSHOT.jar /root/deployment
              echo "Previous JAR restored successfully."
            else
              echo "No previous JAR found! Rollback skipped."
              exit 1
            fi

            echo "Installing Sqitch if not already installed..."
            apt update && apt install -y sqitch libdbd-mysql-perl

            echo "Fetching previous Sqitch migration tag..."
            echo "Listing JAR contents..."
            jar tf /root/deployment/sqitch-test-0.0.1-SNAPSHOT.jar | grep -E 'sqitch\.plan|deploy/|revert/'

            # Extract Sqitch files to a temporary directory
            jar xf root/deployment/sqitch-test-0.0.1-SNAPSHOT.jar sqitch.plan deploy/ revert/
            cp sqitch.plan /root/deployment/sqitch
            cp -r deploy/ revert/ /root/deployment/sqitch


            cd /root/deployment/sqitch
            PREV_TAG=$(sqitch log --reverse -n 2 db:mysql://admin:password%40123@localhost/cicdpipeline | awk 'NR==4 {print $1}')

            if [ -n "$PREV_TAG" ]; then
              echo "Reverting database to $PREV_TAG..."
              sqitch revert db:mysql://admin:password%40123@localhost/cicdpipeline --to $PREV_TAG
              echo "Database rollback successful."
            else
              echo "No previous Sqitch migration found! Skipping DB rollback."
            fi

            echo "Reloading systemd and restarting application..."
            systemctl daemon-reexec
            systemctl start sqitch-spring-service.service
            systemctl status sqitch-spring-service.service || echo "Failed to start service"
