name: Rollback CI/CD Workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to rollback'
        required: true
        default: 'cicd-sqitch'

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: Rollback Database and Restart Application
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 156.67.105.82
          username: root
          password: 1a2s3d4f5g@1993
          envs: DB_PASSWORD
          script: |
            echo "Stopping current application..."
            systemctl stop sqitch-spring-service.service || echo "Service not running"

            echo "Restoring previous JAR..."
            if [ -f "/root/deployment/backups/sqitch-test-0.0.1-SNAPSHOT.jar" ]; then
              cp /root/deployment/backups/sqitch-test-0.0.1-SNAPSHOT.jar /root/deployment
              echo "Previous JAR restored successfully."
            else
              echo "No previous JAR found! Rollback skipped."
              exit 1
            fi

            echo "Installing Sqitch if not already installed..."
            apt update && apt install -y sqitch libdbd-mysql-perl

            echo "Fetching previous Sqitch migration tag..."
            echo "Listing JAR contents..."
            jar tf /root/deployment/sqitch-test-0.0.1-SNAPSHOT.jar | grep -E 'sqitch\.plan|deploy/|revert/'

            # Extract Sqitch files to a temporary directory
            jar xf /root/deployment/sqitch-test-0.0.1-SNAPSHOT.jar BOOT-INF/classes/revert/ BOOT-INF/classes/deploy/ BOOT-INF/classes/sqitch.plan
            cp BOOT-INF/classes/sqitch.plan /root/deployment/sqitch
            cp -r BOOT-INF/classes/revert/ BOOT-INF/classes/deploy/ /root/deployment/sqitch


            cd /root/deployment/sqitch

            # Initialize temp Sqitch project
            sqitch init temp-project --engine mysql

            # Overwrite auto-generated plan with the real one
            cp sqitch.plan sqitch.plan.bak  # just in case
            # No need to copy again if already present

            # Run log on initialized project
            PREV_TAG=$(sqitch log --reverse db:mysql://admin:password%40123@localhost/cicdpipeline | grep '^@' | head -n 2 | tail -n 1 | sed 's/@//')


            if [ -n "$PREV_TAG" ]; then
              echo "Reverting database to $PREV_TAG..."
              sqitch revert db:mysql://admin:password%40123@localhost/cicdpipeline --to $PREV_TAG
              echo "Database rollback successful."
            else
              echo "No previous Sqitch migration found! Skipping DB rollback."
            fi

            echo "Reloading systemd and restarting application..."
            systemctl daemon-reexec
            systemctl start sqitch-spring-service.service
            systemctl status sqitch-spring-service.service || echo "Failed to start service"
